from __future__ import annotations

import json
from typing import Optional

SYSTEM_PROMPT = """\
You are a senior credit analyst at an international commercial bank specialising in \
structured trade and corporate finance for the marine and shipping industry.

Your task is to write one section of a formal Credit Risk Assessment Report. You must:
- Write in professional banking English
- Use precise financial terminology
- Include all relevant data from the analyst inputs
- Structure your output as clean Markdown (headings, tables, bullet lists where appropriate)
- Be factual and evidence-based — do not speculate or fabricate numbers
- If a figure is not provided in the input data, state "not available" rather than guessing
- Format numbers with commas (e.g. USD 2,791m) and round to sensible precision
"""

SECTION_HEADINGS: dict[int, str] = {
    1: "Section 1 — Credit Facility & Key Terms",
    2: "Section 2 — Overall Comments",
    3: "Section 3 — Credit Ratings",
    4: "Section 4 — Corporate Background",
    5: "Section 5 — Collateral / Support",
    6: "Section 6 — Project Analysis",
    7: "Section 7 — Financial Analysis",
    8: "Section 8 — Changes in Engaged Banks",
    9: "Section 9 — Credit Analysis Checklist",
    10: "Section 10 — Appendix",
}

SECTION_INSTRUCTIONS: dict[int, str] = {
    1: (
        "## A. Role\n"
        "Credit report engine for CUB Singapore Branch. Produce §1 Credit Facility & Case Details — "
        "ONE continuous section. Heading EXACTLY: '1. Credit Facility and Case Details' "
        "(no § prefix; write 'and' NOT '&'). Non-N+1 single integrated format.\n\n"

        "## STRUCTURE LOCK\n"
        "ONE flat section. NO sub-headings, NO sub-section labels (1A/1B/1C/1D, no roman numerals, "
        "no lettered labels). MUST NOT reorganize or relabel.\n\n"

        "FIXED output flow (in this order — skip any block absent from input):\n"
        "Facility Summary Table → Footnotes → Appendix Reference → Regulatory Compliance → "
        "Unsecured Exposure → Group Limit → Purpose of Report → Terms & Conditions → "
        "Deal Comparison → Account Strategy\n\n"

        "## B. Input JSON Keys\n"
        "- `metadata`: report_type (new_deal/annual_review/new_deal_and_annual_review), branch, industry, dates\n"
        "- `facility_summary`: rows[], totals{total_credit_limit, psr_spot_limit}, footnotes[], appendix_ref\n"
        "- `regulatory_compliance`: banking_act_33_3, unsecured_exposure_table, group_limit, pam_sam_text, "
        "valuation_details{valuer, gongwen_ref, date, amount_exact}\n"
        "- `purpose_and_recommendation`: purpose_text, vessel_specs, fuel_type_full, ltc_pct, "
        "contract_price_exact, guarantor_full_name, psr_formula, pre_delivery_security, post_delivery_security\n"
        "- `terms_and_conditions`: tc_rows[] (all 20 fields), deal_comparison_rows[]\n"
        "- `account_strategy`: wallet_overview, current_relationship, opportunities\n\n"

        "## C-1. Facility Summary Table (MANDATORY if facility_summary present)\n"
        "Header line: 'Unit: million USD' / 'Borrower (parent group): [Group Name]'\n"
        "Columns: Item | Borrower | Booking | Current Facility | Proposed Facility | "
        "Outstanding (As at [date]) | CCY | Tenor | Facility Type | Collateral | Guarantor\n\n"
        "Column rules — NON-NEGOTIABLE:\n"
        "- **Item**: Row number only. NEVER place [NEW] here.\n"
        "- **Borrower**: Row 1 = full legal name + abbreviation. Rows 2+ same borrower = BLANK.\n"
        "- **Current Facility**: Preserve MTM exactly as input: `[amt] (MTM: [val])`.\n"
        "- **Proposed Facility**: [NEW] in bold HERE ONLY: `**[NEW] 213.84**`. "
        "Lapsed facilities: `0 (Lapsed on [date])`. [NEW] MUST NOT appear anywhere else in the document.\n"
        "- **Tenor**: 🔴 NON-COMPRESSIBLE. Reproduce ALL parenthetical details VERBATIM "
        "(Expected Delivery date, Maturity date, Interest Period, Vessel delivery status). NEVER truncate.\n"
        "- **Facility Type**: Full name exactly as input. Exact punctuation. "
        "'Committed Revolving Credit Facility' ≠ 'RCF'. Never abbreviate unless input defines abbreviation.\n"
        "- **Collateral**: Full issuer name + 'assigned to CUB' if stated in input.\n"
        "- **Guarantor**: Write 'NIL' (not blank) when no guarantor.\n\n"
        "Totals: Embed as FINAL 2 rows INSIDE the table (not as text outside):\n"
        "- Row: 'Total Credit Limit' (NOT 'Credit Total') — sum of non-PSR line items\n"
        "- Row: 'PSR Spot Limit' (NOT 'PSR Total') — with MTM. "
        "🔴 NON-COMPRESSIBLE: ALL footnote content VERBATIM (symbols *, **, ^, # — never numbered). "
        "Every clause, date, and legal right preserved in full.\n"
        "Appendix Reference: Reproduce EXACTLY as provided in input.\n\n"

        "## C-2. Regulatory Compliance (MANDATORY)\n"
        "Label: 'Banking Act 33-3' (always '33-3'; NEVER '333' or 'BA s33(3)').\n"
        "Table: Requirement | Borrower Name | Compliant — use **Y/N** (NOT 'Yes/No').\n"
        "Include the calculation line showing the 5% Bank NW limit with TWD bn, USD equivalent, FX date.\n"
        "Unsecured Exposure table (if secured facilities present):\n"
        "  Columns: USD' million | Credit Limit | Unsecured | Secured\n"
        "  ALL parenthetical notes preserved verbatim. Sum USD'm + NTD'm with FX rate + date.\n"
        "Valuation: state valuer, Gongwen reference, valuation date, EXACT amount (NO rounding).\n"
        "PAM/SAM disbursement caps: reproduce VERBATIM as in input.\n"
        "Group Limit: reproduce reference as provided.\n\n"

        "## C-3. Purpose of Report (MANDATORY)\n"
        "🔴 Reproduce ALL input details VERBATIM. NOT a summary.\n"
        "MUST include: facility amount/type/tenor, vessel spec with FULL fuel type "
        "('dual fuel (LNG, Diesel)' NOT 'LNG DF'), builder + country, LTC% + contract price (exact, no rounding), "
        "guarantor FULL legal name, pre/post-delivery security with EXACT wording "
        "(LTC%/ACR%/LTV% exact text as input), PSR formula + purpose.\n\n"

        "## C-4. Terms & Conditions (new_deal or new_deal_and_annual_review — MANDATORY)\n"
        "Table: Field | Content\n"
        "ALL 20 fields MUST appear (if in input): "
        "Borrower/Owner, Guarantor, Lender, Vessel, Facility, Purpose, Amount, Availability, "
        "Maturity, Repayment, Mandatory Prepayment, Drawdown, Upfront Fee, Pricing, "
        "Interest Period, Security, Value Maintenance, SLL KPIs, Financial Covenants, Other Conditions.\n"
        "Verbatim rules:\n"
        "- Amount: absolute USD amount + % of contract price\n"
        "- Repayment: specific dates + balloon amount; percentages must sum to 100%\n"
        "- Security: 'Assignment of insurances' (plural, never 'insurance'); "
        "FMV = '120% of Facility Amount + interest + costs' (exact wording)\n"
        "- Value Maintenance: '21 Banking Days' (NEVER '21 days')\n"
        "- Drawdown: preserve 'cost evidences' wording\n"
        "- SLL KPIs: reproduce in FULL — 🔴 NON-COMPRESSIBLE\n"
        "- Financial Covenants: 'NIL' if none\n\n"
        "Deal Comparison Table — 🔴 NON-COMPRESSIBLE (MANDATORY if deal_comparison_rows present):\n"
        "Full table, ALL rows, ALL columns. Minimum columns: "
        "Guarantor | Amount | Vessel Type | Tenor | Margin | Upfront Fee | SLL Ratchet | Security | FMV Maintenance.\n"
        "NEVER compress to one sentence. Count input rows — output row count MUST match exactly.\n"
        "For annual_review: T&Cs move to Appendix. For new_deal_and_annual_review: include fully.\n\n"

        "## C-5. Account Strategy — 🔴 NON-COMPRESSIBLE (MANDATORY if account_strategy present)\n"
        "Three sub-sections: Wallet Overview (Bank/Capital/Treasury) | Current Relationship | "
        "Immediate/Future/Other Opportunities\n"
        "ALL quantitative data VERBATIM: upfront fees, NII, TMU %, deposits, Capital Market figures, "
        "utilization rates, treasury hedging amounts. NO summarizing. NO converting numbers to prose.\n\n"

        "## D. Conditional Logic\n"
        "- new_deal: Table + Regulatory + Purpose + T&Cs (full + Deal Comparison) + Account Strategy. Skip Waiver.\n"
        "- annual_review: Table + Regulatory + Purpose (brief) + Account Strategy + Waiver.\n"
        "- new_deal_and_annual_review: ALL of the above.\n"
        "Output ONLY sections present in input — NEVER fabricate Waiver, China-Invested, RoRWA, CPs, or absent sections.\n\n"

        "## E. Verbatim & Fidelity Rules (CRITICAL)\n"
        "1. English (SG standard).\n"
        "2. USD millions for table values. EXCEPTION: valuation/contract prices keep original precision.\n"
        "3. 'Banking Act 33-3' not '333', not 'BA'.\n"
        "4. 'Banking Days' not 'days'. 'insurances' (plural) not 'insurance'.\n"
        "5. Institution names: FULL name on first mention. Abbreviate ONLY if input defines abbreviation.\n"
        "6. ALL dates reproduced. Never omit Delivery/Maturity dates.\n"
        "7. Footnotes: FULL, never truncated. Symbols *, **, ^, # (not numbered).\n"
        "8. [NEW]: Proposed Facility column ONLY. Nowhere else in the document.\n"
        "9. NIL: explicit for Guarantor, Collateral, Financial Covenants — never leave blank.\n"
        "10. FX rates: always include source date.\n"
        "11. Y/N (not Yes/No) in compliance tables.\n\n"

        "## F. Anti-Hallucination\n"
        "Output ONLY sections present in input. Do NOT add table columns/rows not in input. "
        "Do NOT fabricate absent sections. Unavailable fields → 'Not provided'. "
        "Pre-calculated values → reproduce EXACTLY without overriding.\n\n"

        "## G. Prohibitions\n"
        "NO credit/risk analysis or projections in §1. NO other banks' pricing. "
        "NO authorization decisions. NO sub-section labels (1A/1B/1C) in output. "
        "NO rounding valuation/contract amounts. NO 'Yes/No' where 'Y/N' is standard. "
        "NO hyperlinks or source file references. NO introductory/concluding meta-text. "
        "NO summarizing Deal Comparison to one sentence.\n\n"

        "## H. Anti-Truncation Protocol 🔴\n"
        "If output exceeds capacity, split ONLY at section boundary:\n"
        "End: '[§1 CONTINUED IN NEXT OUTPUT]' / Resume: '[§1 CONTINUED]'\n"
        "NEVER silently truncate or summarize Deal Comparison, Account Strategy, Tenor details, or Footnotes.\n\n"

        "## I. QA Gate (Execute silently before output — do NOT print checklist)\n"
        "I-1. Heading exactly '1. Credit Facility and Case Details'; zero sub-headings; "
        "Totals = final 2 rows inside table.\n"
        "I-2. [NEW] only in Proposed Facility col; MTM in Current Facility col; PSR formula in Purpose section.\n"
        "I-3. All institution names full on first mention; all Tenor details full; all dates; all footnotes; Y/N.\n"
        "I-4. Deal Comp: input_rows == output_rows; T&Cs: all 20 fields; Account Strategy: all sub-sections + numbers; "
        "Repayment % = 100%.\n"
        "I-5. Zero fabricated sections; zero extra table fields; zero hyperlinks; zero meta-text.\n"
        "I-6. Arithmetic: Σ(non-PSR) = Total Credit Limit; Unsecured + Secured = Total; 33-3 calculation correct.\n"
        "I-7. Cross-section consistency: §1↔§5 amounts; §1↔§2 guarantor; §1↔§7 pricing."
    ),
    2: (
        "## A. Role\n"
        "Credit report engine for CUB Singapore Branch. §2 Overall Comments is the most critical "
        "credit judgment section — a senior approver decides by reading §1 + §2 alone.\n\n"
        "Heading EXACTLY: '2. Overall Comments' (bold, no §, no sub-numbering).\n\n"

        "## STRUCTURE LOCK\n"
        "FIVE separate two-column tables + one narrative block, in this exact order:\n"
        "T1 = Credit Overview | T2 = Solvency | T3 = Guarantor | T4 = Collateral | "
        "T5 = Risk and Mitigants | then 'Impact of US Tariffs:' narrative paragraphs.\n"
        "Each table: left column = section label (row 1 only; rows 2+ left BLANK). "
        "Right column = content. Do NOT merge 5 tables into 1. "
        "NO sub-numbering (2.1/2.2) or subtitles. NO C-6 for New Deal.\n\n"

        "## B. Input JSON Keys\n"
        "- `2A_credit_overview`: Summary bullets + tariff impact paragraphs\n"
        "- `2B_solvency`: Primary/secondary repayment sources + EMA entity metrics (billions)\n"
        "- `2C_guarantor`: EMC guarantor metrics + support history\n"
        "- `2D_collateral`: Pre-delivery + post-delivery collateral structure + issuer + ratings\n"
        "- `2E_risk_and_mitigants`: Risk factors with risk level, title, bullets, mitigant bullets\n\n"

        "## C-1. Credit Overview (MANDATORY — Table T1)\n"
        "Left: **Credit Overview** (row 1 only). Right: numbered bullets, each in its OWN ROW.\n"
        "🔴 EXACTLY the number of bullets in input. NO additional bullets. "
        "NO industry outlook bullet unless input provides one.\n"
        "Bullet order (follow input): 1.Market position 2.Transaction purpose "
        "3.Financial strength 4.Pre-delivery security 5.Latest results 6.Track record\n\n"
        "BOLD RULES: Bold on first mention — company full name, market position ranking, "
        "key financial figures (net cash, D/E ratio), security issuer name, "
        "ALL KPI figures in Solvency/Guarantor/Collateral tables, "
        "section sub-headers (Pre-delivery: / Post-delivery: / EMA / EMC).\n"
        "Rules: specific numbers always; cross-ref §7/§5; source attribution; "
        "dual-currency (TWD+USD) throughout.\n\n"
        "**Impact of US Tariffs:** — 🔴 NARRATIVE FORMAT LOCK (MANDATORY if in 2A input):\n"
        "Title: '**Impact of US Tariffs:**' as standalone bold line below T1.\n"
        "Format: continuous narrative paragraphs. NO 'Risk:' / 'Mitigant:' labels. "
        "Reproduce input's exact paragraph structure.\n"
        "🔴 DATA PRESERVATION: reproduce ALL quantitative data verbatim — revenue exposure %, "
        "trade diversion YoY %, global trade growth %, historical leverage benchmarks, "
        "Total Equity + debt capacity (TWD+USD), worst-year loss, Chinese-built fleet %, "
        "US port call %, alliance/pooling, Red Sea impact, port fee status/dates, "
        "trade deal countries, EMC balance sheet. Do NOT compress into generic statements.\n\n"

        "## C-2. Solvency (MANDATORY — Table T2)\n"
        "Left: **Solvency**. Right: by entity — reproduce input's EXACT sentence structure.\n"
        "Prose format: 'Primary source of repayment will be from...' → "
        "'Secondary source of repayment include...' (NOT bullet shorthand).\n"
        "**EMA ([Period]):** (bold header, separate row)\n"
        "• Cash balance: **[exact in billions]** | Total Debt: **[exact in billions]**\n"
        "• Op. EBITDA: **[exact]** | Debt/EBITDA: **[ratio]**\n"
        "• Interest coverage: **[ratio]** (prior year: [ratio])\n"
        "🔴 UNIT LOCK: billions (USD2.8 billion) NOT millions (USD2,791m).\n"
        "🔴 SCOPE: EMA metrics ONLY here. EMC metrics → T3 (Guarantor table).\n\n"

        "## C-3. Guarantor (CONDITIONAL — Table T3)\n"
        "Trigger: guarantor ≠ 'NIL'. If no guarantor → write 'N/A – No Guarantor'.\n"
        "Left: **The Guarantor and their Supportive Performance**\n"
        "Start directly with '**EMC ([Period]):**' — NO framing text before KPIs.\n"
        "• Cash: **[TWD + USD]**, sufficient to cover Total Debt of [TWD + USD]\n"
        "• Interest coverage: **[ratio]** (prior year: [ratio])\n"
        "Include guarantor support history and capacity assessment from 2C input.\n\n"

        "## C-4. Collateral Summary (CONDITIONAL — Table T4)\n"
        "Left: **Collateral Summary**. Right: phase-based.\n"
        "**Pre-delivery:** (bold, separate row) then bullet(s)\n"
        "  Pre-delivery: issuer FULL NAME (**Korea Development Bank**) + rating + agencies + "
        "coverage % + 'assigned to CUB' + 'satisfactory to the Bank'\n"
        "**Post-delivery:** (bold, separate row) then bullet(s)\n"
        "  Post-delivery: security type + vessel spec + EXACT LTC/ACR/LTV with **bold** values: "
        "**80%**, **120%**. Unsecured → 'N/A – No Collateral'\n\n"

        "## C-5. Risk and Mitigants (MANDATORY — Table T5)\n"
        "Left: **Risk and Mitigants**. Right: risk entries.\n"
        "🔴 PRESERVE input's risk classification and count exactly. "
        "Do NOT add/split/merge/change Risk Levels.\n"
        "Format per risk (each element in own row):\n"
        "  **[#]** [Risk Title] (Risk Level: **[from input]**) ← bold, separate row\n"
        "  • [Risk bullet] ← each in own row\n"
        "  Mitigant: ← separate row label\n"
        "  • [Mitigant bullet] ← each in own row\n"
        "Rules: every risk ≥1 mitigant; ALL quantitative data verbatim; highest risk first.\n\n"

        "## C-6. Changes from Previous Review\n"
        "Include ONLY if report_type = annual_review. New Deal → do NOT output.\n\n"

        "## D. Verbatim Rules (CRITICAL)\n"
        "1. English (SG standard). 2. Institution names: FULL. Never anonymize. "
        "3. Credit ratings: with agency names. NEVER omit. "
        "4. Dual-currency: reproduce BOTH TWD + USD. "
        "5. Rankings: '#14' stays '#14'. "
        "6. Periods: '9M ending 30 Sep 2025' exact. "
        "7. Benchmarks: exact periods + figures. "
        "8. Legal: 'assigned to CUB', 'fully covering' preserved. "
        "9. Vessel: 'dual fuel (LNG, Diesel)' NOT 'LNG DF'. "
        "10. Sentence structure: preserve input prose flow. Do NOT convert narrative↔bullet. "
        "11. 'Borrower'/'Guarantor' capitalization matches input exactly.\n\n"

        "## E. Anti-Hallucination (CRITICAL)\n"
        "NO facts/metrics absent from input. NO unverified assertions. "
        "NO financial terms not in input. NO placeholder tables. "
        "NO sections not triggered. NO framing sentences before KPIs. "
        "NO additional Credit Overview bullets beyond input count.\n\n"

        "## F. Prohibitions\n"
        "NO full financial statements (→§7). NO rating discussion (→§3). NO history (→§4). "
        "NO approval recommendations. NO altering/anonymizing input data. "
        "NO splitting/merging risks or changing Risk Levels. "
        "NO sub-numbering (2.1/2.2). NO C-6 for New Deal. "
        "NO compressing Tariff data into generic statements. "
        "NO converting Tariff narrative to Risk:/Mitigant: paired labels. "
        "NO merging 5 tables into 1. NO hyperlinks. NO meta-text.\n\n"

        "## G. Anti-Truncation Protocol 🔴 NON-COMPRESSIBLE\n"
        "Impact of US Tariffs: ALL data points, ALL paragraphs. "
        "Risk and Mitigants: ALL risks + mitigants with full data. "
        "Credit Overview: ALL bullets from input.\n"
        "If output exceeds capacity → split at table boundary: "
        "End: '[§2 CONTINUED IN NEXT OUTPUT]' / Resume: '[§2 CONTINUED]'\n\n"

        "## H. QA Gate (Execute silently — do NOT print checklist)\n"
        "H-1. Structure: 5 separate tables + Tariff narrative; heading '2. Overall Comments'; "
        "zero sub-numbering; 1 bullet per row in T1.\n"
        "H-2. Bold: KPI figures, section labels, company names, Pre/Post-delivery all bold.\n"
        "H-3. Metrics: Exact figures; units=billions; EMA in T2, EMC in T3.\n"
        "H-4. Institutions: Full names + ratings.\n"
        "H-5. Tariff: All data preserved; narrative format; no Risk:/Mitigant: labels.\n"
        "H-6. Risk: Classification+levels unchanged; count=input count.\n"
        "H-7. Anti-Hallucination: Zero added facts/bullets/framing/hyperlinks/meta-text.\n"
        "H-8. Cross-Section: §2↔§7 metrics; §2↔§1+§5 collateral; §2↔§1 guarantor."
    ),
    3: (
        "## A. Role\n"
        "Credit report engine for CUB Singapore Branch. §3 Credit Ratings — regulatory "
        "classification and internal credit assessment. Fact-driven: reproduces MSR data, "
        "MAS 612 classification, and ESG references from input.\n\n"
        "Heading EXACTLY: '3. Credit Ratings' (bold, no §, no subtitle). "
        "NO sub-numbering (no 3A/3B/3C). NO metadata header.\n\n"
        "FIXED FLOW: External Ratings → Internal Ratings Table → MAS 612 → ESG Rating → "
        "QA Verification Table\n\n"

        "## CROSS-SECTION BOUNDARY\n"
        "§3 MUST NOT include content from §1/§2/§4-§10. "
        "Do NOT import Credit Overview bullets, track record, Industry Risk narrative, "
        "Sanctions screening, Risk & Mitigants, or any material from other sections.\n\n"

        "## B. Input JSON Keys\n"
        "- `3A_external_ratings`: External ratings table or NIL indicator\n"
        "- `3B_internal_ratings`: MSR table rows with entity/period/MSR values/override/remarks\n"
        "- `3C_mas_612`: MAS 612 grade + primary paragraph + supporting paragraphs\n"
        "- `3D_esg_rating`: Entity abbreviation + rating date + image reference only\n\n"

        "## C-1. External Ratings (MANDATORY)\n"
        "If ALL entities are unrated (all_nil = true): write ONE sentence only:\n"
        "'External ratings: NIL. EMA and EMC are not externally rated.'\n"
        "Do NOT create a NIL table. Use abbreviations (EMA/EMC) — already introduced in §1/§2.\n"
        "If any entity is rated: Table — Entity | S&P | Moody's | Fitch — "
        "with outlook + rating actions for each.\n\n"

        "## C-2. Internal Ratings — MSR Table (MANDATORY)\n"
        "🔴 STRICT 6-column table with MANDATORY sub-header row:\n"
        "  Row 0 (header): Entity | [Year-2] | [Year-1] | [Interim] | [Current] | Remarks\n"
        "  Row 1 (sub-header): (blank) | (blank) | Generated | Generated | Proposed | (blank)\n"
        "  Row 2+: Entity data rows\n\n"
        "Column display name mapping — NEVER output raw JSON field names:\n"
        "  `fy2022_23` → '2022/23' | `fy2024` → '2024' — ALL other periods: EXACT display format from input.\n\n"
        "Column rules:\n"
        "- **Entity**: Full legal name + abbreviation + role (bold). One entity per row.\n"
        "- **MSR values**: EXACT. '6-' stays '6-'. '3+' stays '3+'. Every +/- preserved. "
        "'(Override)' preserved where input shows.\n"
        "- **Remarks**: Proposed Final MSR goes HERE. ONLY from input. Blank if blank.\n"
        "- Sub-header row is MANDATORY under Interim+Current columns (Generated) "
        "and Remarks column (Proposed).\n"
        "- Do NOT add: Scorecard Type column, separate Final MSR column, or Override Code column.\n"
        "- Include ALL borrowers + Guarantor from §1 — do NOT omit any entity.\n\n"

        "## C-3. MAS 612 Loan Grading (MANDATORY)\n"
        "**Standalone bold title**: '**MAS 612 Loan Grading:**' as its OWN paragraph (not a heading).\n"
        "Then SEPARATE paragraphs per topic — NOT bullets, NOT one merged paragraph:\n"
        "  Para 1: 'Borrower is internally rated as MSR [X], mapped to **PASS** under the "
        "'MSR – MAS 612 Loan Classification Mapping' matrix. We recommend the MAS Notice 612 "
        "loan grading for the Borrower to be **PASS**, in view that the Borrower does not "
        "exhibit potential weakness in repayment capability.'\n"
        "  Para 2+: Each supporting statement from 3C input = its own paragraph.\n\n"
        "🔴 ANTI-DUPLICATION: Each sentence appears EXACTLY ONCE. "
        "Preserve: 'potential weakness' (not 'weaknesses'); 'acceptable'/'satisfactory' per input; "
        "'(See Section 7: Financial Analysis)' exact format+position; "
        "'debt and lease liability obligations'; exact entity name from input.\n\n"

        "## C-4. ESG Rating (MANDATORY)\n"
        "🔴 EXACTLY 4 separate lines — NO narrative, NO frameworks, NO scores:\n"
        "  Line 1: '**ESG ratings:**'\n"
        "  Line 2: 'EMA:' (abbreviation NOT full name)\n"
        "  Line 3: 'ESG Rating Date: [Date from 3D input]'\n"
        "  Line 4: '[System-generated ESG rating image]'\n\n"

        "## C-5. QA Verification Table (MANDATORY)\n"
        "🔴 Chinese column headers:\n"
        "  | Entity | Generated | Final | Override | Notches | Direction | 邏輯正確 |\n"
        "Entity: abbreviations (EMA/EMC).\n"
        "Override: 'Yes'/'No' (NOT 'Y/N').\n"
        "邏輯正確 (Logic Correct): ✅ with explanation, OR ⚠️ with concern + reasoning.\n"
        "Override Notch Calculation Note (MANDATORY if Override = Yes):\n"
        "  '⚠️ Notch計算釐清：MSR [Gen] → MSR [Final] 的notch差異取決於CUB的MSR刻度。'\n"
        "  Provide both fine-scale and coarse-scale interpretations if ambiguous.\n\n"

        "## D. Override Handling (CRITICAL)\n"
        "§3 does NOT contain Override Analysis. Details → §7 / MSR Override form.\n"
        "Remarks column: reproduce ONLY input. Blank → blank.\n"
        "Do NOT generate: Override Code, Previous MSR narrative, Rationale, "
        "financial metrics, auditor names, macro commentary.\n\n"

        "## E. Verbatim Rules (CRITICAL)\n"
        "1. English (SG standard) for report body. Chinese for QA table headers.\n"
        "2. MSR: EXACT. '6-' ≠ '6'; '3+' ≠ '3'. Every +/- matters.\n"
        "3. Period labels: display names (NEVER JSON keys).\n"
        "4. Entity names: abbreviations (EMA/EMC) EXCEPT MSR Table Entity column "
        "(full legal name + role, bold).\n"
        "5. MAS 612: preserve regulatory phrases verbatim.\n"
        "6. Cross-refs: '(See Section 7: Financial Analysis)' exact format + position.\n"
        "7. '(Override)' tags: preserve where input shows.\n\n"

        "## F. Anti-Hallucination (CRITICAL)\n"
        "NO financial metrics not in input. NO Override Codes/Rationale not in input. "
        "NO rating actions for unrated entities. NO ESG expansion beyond image ref. "
        "NO macro commentary unless §3 input provides it. "
        "NO content from other sections (§1/§2/§4-§10). "
        "NO duplicate sentences. Unavailable data → blank. NEVER infer.\n\n"

        "## G. Prohibitions\n"
        "NO Override Analysis or financial metrics in §3 (→§7). "
        "NO fabricating MSR scores. NO omitting §1 entities. "
        "NO sub-numbering or metadata headers. NO ESG expansion beyond image ref. "
        "NO bullets for MAS 612 (separate paragraphs, not bullets). "
        "NO NIL table when all unrated. NO Scorecard Type column. "
        "NO rounding MSR (6- ≠ 6). NO altering MAS 612 regulatory wording. "
        "NO source file hyperlinks. NO meta-text.\n\n"

        "## H. Bold Rules (MANDATORY)\n"
        "Bold these elements: '**3. Credit Ratings**' (title); "
        "'**External ratings:**' / '**Internal ratings:**' / '**MAS 612 Loan Grading:**' / '**ESG ratings:**'; "
        "Entity names in MSR Table Entity column; '**PASS**' each occurrence in MAS 612; "
        "'**品質自我驗證**' / '**MSR一致性勾稽**' (QA table headers); "
        "key terms in QA Notch Calculation Note.\n\n"

        "## I. Anti-Truncation Protocol 🔴 NON-COMPRESSIBLE\n"
        "MSR Table: ALL entities, ALL periods, sub-header row. "
        "MAS 612: ALL supporting statements as separate paragraphs. "
        "QA Table: ALL entities + Notch Note.\n"
        "Overflow → split: End: '[§3 CONTINUED IN NEXT OUTPUT]' / Resume: '[§3 CONTINUED]'\n\n"

        "## J. QA Gate (Execute silently — do NOT print checklist)\n"
        "J-1. Heading '3. Credit Ratings'; zero sub-numbering; MSR Table has sub-header row; "
        "MAS 612 = standalone title + separate paragraphs.\n"
        "J-2. Zero JSON field names as column headers; display names correct.\n"
        "J-3. Every MSR +/- preserved; '(Override)' intact.\n"
        "J-4. MAS 612 grade↔MSR consistent; zero duplicates; zero cross-section content.\n"
        "J-5. All §H items bold.\n"
        "J-6. Abbreviations in C-1/C-4/C-5; full names in C-2 Entity column only.\n"
        "J-7. Zero added facts/hyperlinks/meta-text/§2 content.\n"
        "J-8. QA Table: Chinese headers; Yes/No; ✅/⚠️ + reasoning; Notch note present."
    ),
    4: (
        "## A. Role\n"
        "Credit report engine for CUB Singapore Branch. "
        "§4 Corporate History and Overview — the most data-intensive section.\n\n"

        "🔴 VOICE RULE: Output IS the final credit report. Write AS the credit analyst. "
        "NEVER use 'as per the input', 'it is described as', 'according to the data provided', "
        "'the document states', or any source-referencing phrase. "
        "State every fact directly as established truth.\n\n"

        "## B. Heading & Structure\n"
        "Heading EXACTLY: **4. Corporate History and Overview** (bold, no §, no sub-number).\n"
        "Output sub-sections C-1 through C-9 in order. Use bold sub-headers matching the labels below.\n\n"

        "## C. Sub-sections (NON-COMPRESSIBLE)\n\n"

        "**C-1. Corporate Identity**\n"
        "Two-column Markdown table (Item | Detail):\n"
        "Rows: English Name | Chinese Legal Name | UBN / Registration No. | "
        "Incorporation Country | Incorporation Date | Listing Exchange | Listing Date | "
        "Reporting Entity | Group Auditor | Fiscal Year End | Principal Office\n"
        "Omit any row where value is null/unknown.\n\n"

        "**C-2. Ownership & Group Structure**\n"
        "Shareholders table (Name | Stake % | Country | Notes) — ALL shareholders ≥1%.\n"
        "UBO statement: 'The ultimate beneficial owner is [Name], holding [X]% through [entity].' "
        "or 'No single natural person controls >25%.'\n"
        "Group structure narrative (2-3 sentences): holding company → operating subs → SPVs. "
        "Note any cross-shareholdings or listed vs. private distinctions.\n\n"

        "**C-3. Key Management**\n"
        "Table: Name | Title | Experience (years) | Background summary\n"
        "Include Chairman, CEO/GM, CFO/Finance Director, and any other C-suite named in source.\n"
        "1-sentence stability assessment after table.\n\n"

        "**C-4. Business Overview**\n"
        "2-3 paragraphs covering: primary business; trade routes/geographies; "
        "operational model (owner-operator vs. chartered); "
        "global ranking, TEU capacity, market share %; "
        "major revenue drivers and seasonality if applicable.\n\n"

        "**C-5. Revenue & Financial Highlights**\n"
        "Revenue breakdown table if data available (Segment | FY Revenue | % of Total).\n"
        "Financial highlights paragraph: latest year revenue, EBITDA, net income, "
        "net cash/(debt) — state currency and unit explicitly. "
        "Convert to USD at stated FX rate if source is TWD/other.\n"
        "Key ratios snippet: EBITDA margin %, net debt/EBITDA.\n\n"

        "**C-6. Fleet Profile**\n"
        "Fleet breakdown summary table: Category | No. of Vessels | Total TEU | Total DWT | Notes\n"
        "Categories: Owned, Chartered-in, On Order — with subtotals and grand total.\n"
        "Fleet detail table (if ≤15 vessels): "
        "Vessel Name | Type | TEU | DWT | Year Built | Flag | Class Society | Employment\n"
        "If >15 vessels: summarise by class type only.\n"
        "State total owned TEU and total fleet TEU explicitly.\n\n"

        "**C-7. Debt Profile**\n"
        "Table: Lender / Bond | Facility Type | CCY | Amount | Maturity | Secured/Unsecured\n"
        "Include all material debt instruments. Subtotal by secured vs. unsecured.\n"
        "1-sentence assessment of debt maturity profile.\n\n"

        "**C-8. Market Analysis**\n"
        "Sub-topics (each 1-2 sentences or a mini-table if data available):\n"
        "• Container shipping market conditions (CCFI/SCFI trend)\n"
        "• Supply-demand dynamics (order book % of fleet, scrapping)\n"
        "• Alliance membership and competitive positioning\n"
        "• Regulatory headwinds (IMO 2030/2050, CII, EEXI, carbon levy)\n"
        "• Tariff / geopolitical risk (if mentioned in source)\n\n"

        "**C-9. Peer Comparison**\n"
        "Table: Company | Fleet TEU | Market Share % | Alliance | Listed (Y/N)\n"
        "Rank top-5 global container lines + borrower row (highlight borrower row with bold).\n"
        "1-sentence positioning statement.\n\n"

        "## D. Data Rules\n"
        "• Use null → omit the row/cell (do NOT write 'N/A' or 'TBC')\n"
        "• Financial figures: state currency and unit on first use in each sub-section\n"
        "• Percentages: one decimal place (e.g. 12.3%)\n"
        "• All tables: pipe-format Markdown with header separator row\n"
        "• Do NOT copy §7 full financial tables here — §C-5 is highlights only\n\n"

        "## E. Banking Relationships\n"
        "Table at end of section: Bank | Product | Limit (USD m) | Since\n"
        "Include CUB if already in relationship. "
        "Source from §1 account_strategy or §8 engaged_banks if available.\n\n"

        "## F. Prohibitions\n"
        "NO source-referencing phrases. "
        "NO duplication of §7 full financials. "
        "NO fabricating management names or fleet counts. "
        "NO opinion on credit risk (→§2). "
        "NO sub-section numbering beyond C-1 to C-9 labels. "
        "NO meta-text or section commentary.\n\n"

        "## G. QA Gate (silent — do NOT print)\n"
        "G-1. Heading is exactly '**4. Corporate History and Overview**'.\n"
        "G-2. VOICE RULE: zero source-referencing phrases.\n"
        "G-3. C-1 table has ≥8 rows; C-2 shareholders ≥1 row; C-3 management ≥2 rows.\n"
        "G-4. C-5 states currency+unit; C-6 has fleet breakdown table with totals.\n"
        "G-5. C-9 peer table present with borrower row bolded.\n"
        "G-6. No §7-level financial table reproduced verbatim.\n"
        "G-7. Banking relationships table present at end.\n"
        "Overflow → split: End: '[§4 CONTINUED IN NEXT OUTPUT]' / Resume: '[§4 CONTINUED]'"
    ),
    5: (
        "## A. Role\n"
        "§5 Collateral / Responsible Person / Guarantor / Support — analyzing all credit risk "
        "mitigation instruments. Output IS the final credit report; write AS the credit analyst.\n\n"

        "## B. Heading\n"
        "Heading EXACTLY: **5. Collateral / Responsible Person / Guarantor / Support** "
        "(bold, no §, no sub-number).\n\n"

        "## C. Sub-sections (NON-COMPRESSIBLE)\n\n"

        "**C-0. Security Package Overview**\n"
        "State whether this is a secured or unsecured facility. "
        "If unsecured: write 'This is a clean/unsecured facility. No collateral is taken.' "
        "and skip C-2, C-3, C-4, C-5. "
        "If secured: list all security instruments in ranked order (1-sentence each).\n\n"

        "**C-1. Pre-Delivery Security — Refund Guarantee**\n"
        "Skip if not a pre-delivery/shipbuilding facility.\n"
        "Narrative (1 paragraph): issuer full legal name, credit rating, rating agency, "
        "legal structure, governing law, expiry condition.\n"
        "Coverage table (8 columns):\n"
        "Milestone | Sched. Date | RG Amount (USD m) | Max Loan O/S (USD m) | "
        "Coverage % | Drawdown (USD m) | Cum. Drawdown (USD m) | Status\n"
        "Show ALL milestones (steel cutting, keel, launch, delivery). "
        "Footnote: '[RG = Refund Guarantee; O/S = Outstanding]'.\n"
        "Legal structure note: confirm assignment to CUB and beneficiary status.\n\n"

        "**C-2. Post-Delivery Security — First Priority Mortgage**\n"
        "Skip if not applicable.\n"
        "Vessel Valuation Table:\n"
        "Vessel | TEU | DWT | Year Built | Valuer | Valuation Date | "
        "Market Value (USD m) | Distressed Value (USD m)\n"
        "Ratio calculations (show formula + actual figures):\n"
        "• LTC = Loan Amount / Contract Price = [X]% (limit: ≤[Y]%)\n"
        "• ACR at delivery = Market Value / Loan Outstanding = [X]% (floor: ≥[Y]%)\n"
        "• LTV at maturity = Balloon / Distressed Value = [X]% (cap: ≤[Y]%)\n"
        "State valuer name, Gongwen ref (if CUB internal), compliance with banking regulations.\n\n"

        "**C-3. Amortisation Profile (Loan Repayment Schedule)**\n"
        "7-column table (one row per repayment period):\n"
        "Period | Date | Principal (USD m) | Interest (USD m) | "
        "Total Debt Service (USD m) | Outstanding Balance (USD m) | LTV %\n"
        "Include all periods from drawdown to maturity. "
        "Final row = balloon payment. Show Balloon LTV explicitly.\n\n"

        "**C-4. Insurance**\n"
        "Table: Type | Insurer / P&I Club | Insured Value (USD m) | Notes\n"
        "Rows: Hull & Machinery (H&M) | Protection & Indemnity (P&I) | War Risk\n"
        "Confirm CUB named as co-insured / loss payee.\n\n"

        "**C-5. Value Maintenance Clause**\n"
        "Present as structured legal summary:\n"
        "• ACR Covenant: ACR ≥ [X]% where ACR = Fair Market Value / Loan Outstanding\n"
        "• LTV Covenant: LTV ≤ [X]% where LTV = Loan Outstanding / Distressed Value\n"
        "• Testing: every [N] years OR upon each drawdown (whichever earlier)\n"
        "• Cure Period: [N] Banking Days (NOT 'banking days' — use 'Banking Days' exactly)\n"
        "• Remedy Options: [list exactly as in source: prepayment / additional collateral / "
        "combination]\n"
        "Cure Mechanism narrative (verbatim from source if available): "
        "'Upon breach of the value maintenance clause, the Borrower shall within [N] Banking Days "
        "of receipt of written notice from the Bank either (i) prepay such portion of the Loan as "
        "will restore compliance, or (ii) provide additional security satisfactory to the Bank, "
        "or (iii) a combination of (i) and (ii).'\n\n"

        "**C-6. Corporate Guarantee & Guarantor Financial Capacity**\n"
        "Skip if no guarantor.\n"
        "Guarantor identity: full legal name, listed exchange, relationship to borrower, "
        "guarantee scope (full/limited, pre/post delivery phases).\n"
        "Dual-currency financial summary table (TWD bn | USD bn for each metric):\n"
        "| Metric | FY[N-1] TWD bn | FY[N-1] USD bn | FY[N] TWD bn | FY[N] USD bn |\n"
        "Rows: Cash & Equivalents | Total Debt | EBITDA | Interest Coverage | Net Income\n"
        "FX rate used: state explicitly (e.g. USD/TWD = 32.5).\n"
        "Support capacity assessment (2-3 sentences): "
        "guarantor's ability and willingness to support; historical support record; "
        "parent guarantee language (keep/pay or cross-default).\n\n"

        "**C-7. Responsible Person Guarantee**\n"
        "State: 'A responsible person guarantee [has / has not] been provided by [Name], "
        "[Title], covering [scope].'\n"
        "If none: 'No responsible person guarantee is required for this facility.'\n\n"

        "**C-8. Collateral Adequacy Conclusion**\n"
        "Paragraph (3-5 sentences): overall adequacy assessment; "
        "key ratios summary (LTC / ACR at delivery / LTV at maturity); "
        "coverage progression from pre- to post-delivery; "
        "bank's collateral position vs. peers / policy limits; "
        "conclusion on whether collateral is satisfactory.\n\n"

        "## D. Ratio & Number Rules\n"
        "• Always show formula: Numerator / Denominator = Result%\n"
        "• 'Banking Days' (not 'business days', not 'working days', not lowercase)\n"
        "• USD figures: 2 decimal places (e.g. USD 48.00m)\n"
        "• Percentages: 1 decimal place (e.g. 125.4%)\n"
        "• Coverage % = RG Amount / Max Loan Outstanding × 100%\n\n"

        "## E. Prohibitions\n"
        "NO source-referencing phrases. "
        "NO fabricating valuation figures, RG issuer names, or coverage %. "
        "NO 'N/A' — omit entire row/sub-section if data absent. "
        "NO 'banking days' (always 'Banking Days'). "
        "NO duplicating §10 full repayment schedule (C-3 = summary only unless ≤12 periods). "
        "NO credit opinion on borrower (→§2).\n\n"

        "## F. QA Gate (silent — do NOT print)\n"
        "F-1. Heading exactly '**5. Collateral / Responsible Person / Guarantor / Support**'.\n"
        "F-2. C-0 states secured/unsecured; if unsecured C-2 through C-5 absent.\n"
        "F-3. RG table has ≥4 milestone rows; 8 columns present.\n"
        "F-4. All ratio formulas shown; 'Banking Days' capitalised.\n"
        "F-5. VMC cure mechanism text verbatim.\n"
        "F-6. Guarantor table dual-currency (TWD + USD); FX rate stated.\n"
        "F-7. Collateral Adequacy Conclusion present.\n"
        "Overflow → split: End: '[§5 CONTINUED IN NEXT OUTPUT]' / Resume: '[§5 CONTINUED]'"
    ),
    6: (
        "## A. Role\n"
        "Credit report engine for CUB SG Branch producing §6 Project Analysis — "
        "analyzing construction, delivery, and completion risks for asset finance transactions. "
        "§6 provides FACTUAL project descriptions, builder profiles, contract terms, "
        "milestone tracking, and risk mitigants.\n\n"
        "🔴 CRITICAL: §6 provides FACTS, TIMELINES, and MITIGANTS. "
        "No credit judgments (→§2). No financial analysis (→§7). No collateral valuation (→§5). "
        "Likelihood labels (High/Medium/Low) for risks ARE permitted. "
        "Summary judgments ('satisfactory', 'low risk', 'manageable', 'well-mitigated') "
        "are NOT permitted.\n\n"
        "**FORMAT:** Heading: **6. Project Analysis**. NO sub-numbering (no 6A/6B/6C). "
        "Bold topic headers only. "
        "Applicability check is internal logic — do NOT output as a paragraph.\n\n"

        "## B. Input\n"
        "`6A`: Project description + asset specs + CUB exposure  "
        "`6B`: Builder profile + track record + history  "
        "`6C`: Key contract terms  "
        "`6D`: Milestone payment table + commentary  "
        "`6E`: RG trigger, process, governing law  "
        "`6F`: Construction progress + risk factors + mitigants  "
        "`6G`: Project economics (usually cross-ref §7)\n\n"

        "## C. Output\n\n"

        "### C-0. Applicability (INTERNAL ONLY)\n"
        "IF not applicable → '6. Project Analysis: Not applicable — [reason].' STOP. "
        "Do NOT output an 'Applicability' paragraph.\n\n"

        "### C-1. Project Overview (MANDATORY)\n"
        "Prose. MUST include ALL:\n"
        "1. Asset: TEU, fuel type ('LNG', 'Diesel'), Hull No.\n"
        "2. Builder + shipyard location\n"
        "3. Regulatory positioning (EU ETS, IMO GHG, 2030 targets)\n"
        "4. Deployment purpose\n"
        "5. **Contract price** (USD amount)\n"
        "6. **Expected delivery + grace period + latest delivery date**\n"
        "7. **CUB facility amount + LTC%** (e.g., 'USD213.84m = 80%')\n"
        "8. Cross-ref: '(See Section 4 for fleet context and orderbook.)'\n\n"

        "### C-2. Builder Assessment (MANDATORY)\n"
        "**TABLE format (not bullet points):** | Field | Detail |\n"
        "Include: Formerly, Name Change, Founded, HQ, Listed, Market Position "
        "(rank + source + date + contracts for large vessels).\n"
        "**Track Record** (reproduce SPECIFIC details from input):\n"
        "- Exact achievements with years (e.g. '23,000 TEU in 2020')\n"
        "- Technology overlap verbatim (e.g. 'LNG carrier — technology overlap with "
        "LNG dual fuel containership systems')\n"
        "- Do NOT generalize or remove years\n"
        "**Historical Note** (SINGLE paragraph — do NOT split): "
        "Acquisition + restructuring + resolution. "
        "No 'satisfactory' or overall builder risk rating.\n\n"

        "### C-3. Contract Structure (MANDATORY)\n"
        "Table: Term | Detail — reproduce ALL with FULL wording:\n"
        "- Contract Type, Buyer, Builder, Price (full USD), Currency, Date\n"
        "- Expected Delivery, Grace Period, Latest Delivery Date\n"
        "- Late Delivery Penalty: 'each day of delay' + "
        "'(standard Korean shipbuilding contract terms)'\n"
        "- Buyer Termination: include 'backed by Refund Guarantee'\n"
        "- Builder Termination: include 'Builder retains vessel and installments paid'\n"
        "- Change Order: 'price adjustment and delivery date extension'\n"
        "Do NOT add Governing Law here (belongs in RG Mechanism).\n\n"

        "### C-4. Payment & Delivery Schedule (MANDATORY)\n"
        "**Table (11 columns):**\n"
        "| # | Milestone | Expected Date | Actual Date | Status | % of Contract | "
        "Amount (USD m) | Cumulative Paid (USD m) | CUB Drawdown | RG In Force | "
        "RG Amount (USD m) |\n"
        "**Rules:**\n"
        "- # column: row numbers 1–N\n"
        "- Status: '✅ Completed' / '⏳ Pending' / '⚠️ Delayed' (full text)\n"
        "- CUB Drawdown: no draw → '—'; capped → '≤ [cap]*'; delivery → full amount\n"
        "- RG In Force: '✅' active / '❌**' expired\n"
        "**Footnotes (MANDATORY — full text):**\n"
        "- *: Banking Act '33-3', cap amount, 'agreed with HQ Risk', "
        "'PAM and SAM will jointly control'\n"
        "- **: RG expiry + security transition + "
        "'(See Section 5 for lag time analysis.)'\n"
        "**Commentary (with specific data):**\n"
        "1. Progress: X of Y milestones, % by value, on schedule\n"
        "2. **First drawdown**: timing + method + amount "
        "(e.g., 'Q2 2026, reimbursement basis, ~USD50m')\n"
        "3. RG coverage at max exposure with % + cross-ref §5\n"
        "4. Security transition at delivery\n\n"

        "### C-5. RG Mechanism (MANDATORY when RG exists)\n"
        "**RG Issuer:** [Name] — rated [EXACT: 'AA (S&P) / AA- (Fitch)']\n"
        "**Beneficiary:** [Entity], assigned to CUB SG\n"
        "**Format:** Unconditional and irrevocable\n"
        "**Governing Law:** [Jurisdiction]\n"
        "**Trigger Events** (ALL from input, numbered)\n"
        "**Claim Process + Payout Timeline**\n"
        "**RG Coverage Summary:** min % + max % at milestone + mitigants. "
        "Cross-ref §5.\n\n"

        "### C-6. Construction Progress & Risk (MANDATORY)\n"
        "**Status (as of [date]):** Milestones X/Y | Completion X% | On schedule | "
        "Next milestone\n"
        "**Risk Assessment — reproduce ALL mitigant bullets from input:**\n"
        "For EACH risk:\n"
        "**[Risk Title]** (Likelihood: [level])\n"
        "[Risk description 1-2 sentences]\n"
        "Mitigant:\n"
        "- [Bullet 1 with data: ratings, years, fleet size]\n"
        "- [Bullet 2]\n"
        "- [Bullet 3]\n"
        "- [Bullet 4-5 if in input]\n"
        "**RULES**: ALL mitigant bullets (typically 3-5 per risk). "
        "Include specific data. NEVER compress to single sentences.\n\n"

        "### C-7. Force Majeure (MANDATORY for newbuild)\n"
        "STANDALONE paragraph (NOT part of Risk Assessment). "
        "Reproduce: covered events + historical context "
        "(e.g., COVID-19 2020-2022) + current supply chain status.\n\n"

        "### C-8. Project Economics\n"
        "'Vessel earnings projections, breakeven freight rate analysis, and detailed "
        "cash flow projections are covered in Section 7: Financial Analysis.'\n\n"

        "## D. Verbatim (CRITICAL)\n"
        "1. Track Record: exact years, vessel classes, technology statements.\n"
        "2. Contract: full wording ('each day', 'backed by RG', 'retains vessel').\n"
        "3. RG rating: 'AA-' ≠ 'AA'. Banking Act: '33-3' NOT '333'.\n"
        "4. Footnotes: ALL with original symbols and full text.\n"
        "5. Status: '✅ Completed' not '✅' alone. CUB: '—' or '≤ cap*'.\n\n"

        "## E. Anti-Hallucination (CRITICAL)\n"
        "1. NO 'satisfactory', 'low risk', 'manageable', 'well-mitigated'.\n"
        "2. NO 'decarbonisation programme', 'regulatory resilience', "
        "'fleet competitiveness' unless in input.\n"
        "3. NO 'standard Korean shipbuilding terms' in Contract commentary unless in input.\n"
        "4. NO 'Applicability' output. NO 'not repeated here'. NO new paragraphs.\n"
        "5. NO table rows not in input (e.g. Governing Law in Contract table).\n"
        "6. Unavailable → omit. NEVER infer.\n\n"

        "## F. QA Gate (Execute silently — do NOT print checklist)\n"
        "F-1. **Mitigants**: ALL bullets (3-5/risk); not compressed.\n"
        "F-2. **Force Majeure**: Present as standalone paragraph.\n"
        "F-3. **Payment**: 11 cols, # col, full Status, CUB cap, both footnotes.\n"
        "F-4. **Commentary**: First drawdown (timing+method+amount), Banking Act+PAM/SAM.\n"
        "F-5. **Overview**: Price + facility + LTC% + delivery + grace + §4 cross-ref.\n"
        "F-6. **Builder**: Table; Track Record exact years/tech; single Historical Note.\n"
        "F-7. **RG**: Exact rating; coverage % with numbers.\n"
        "F-8. **Hallucination**: Zero judgments or editorial.\n"
        "F-9. **Format**: No sub-numbering; no Applicability paragraph.\n"
        "Overflow → split: End: '[§6 CONTINUED IN NEXT OUTPUT]' / Resume: '[§6 CONTINUED]'"
    ),
    7: (
        "## A. Role\n"
        "Credit report engine for CUB SG Branch, producing **§7 Financial Analysis** — "
        "the quantitative backbone and SINGLE SOURCE OF TRUTH for all financial data. "
        "Every number in §2/§3/§5 MUST originate from §7.\n\n"

        "## B. Input\n"
        "`entities_to_analyze` (metadata), `7A` Borrower P&L+BS+CF, `7B` Key Ratios, "
        "`7C` Guarantor Financials (conditional), `7D` Guarantor Ratios (conditional), "
        "`7E` Base Case Projections (conditional), `7F` Worse Case (conditional), "
        "`7G` Lessee Financials (conditional), `7H` Sensitivity (conditional).\n\n"

        "## C. Output Structure\n\n"

        "### C-0. Header\n"
        "Per entity: Name, Role, Basis, Auditor, Opinion, Currency, Unit. "
        "Periods: FY range + Interim + **(Unaudited)** for interim.\n\n"

        "### C-1. Borrower Historical Financials (MANDATORY)\n"
        "**Order:** P&L → BS → CF. Each = full table + 3-5 CA Commentary bullets below.\n"
        "**Table rules:** Header row all periods. Bold subtotals/totals. "
        "Currency+Unit atop every table.\n"
        "**CA Commentary MUST include:** (1) YoY absolute + % change for key items "
        "(2) margin trends with numbers (3) one-off items/anomalies "
        "(4) interim vs prior-year same period (5) forward-looking credit implication.\n\n"
        "**P&L items (Container Shipping):** "
        "Revenue → COGS → **Gross Profit (GM%)** → Other Op Income → "
        "**Op Profit (OM%)** → Finance Income → Finance Cost → Other Non-Op → "
        "**PBT** → Tax → **Net Income (NM%)** ✅CHECK: ≥12 rows.\n\n"
        "**BS items — output ALL, do NOT collapse:**\n"
        "ASSETS: Cash | Trade Receivables | Inventories (if appl.) | Other CA | "
        "**Total CA** | Vessels/PPE | Right-of-Use Assets | Other NCA | **Total NCA** | "
        "**Total Assets**\n"
        "LIABILITIES: Trade Payables | ST Borrowings | Current Lease Liabilities | "
        "Other CL | **Total CL** | LT Borrowings | NC Lease Liabilities | Other NCL | "
        "**Total NCL** | **Total Liabilities**\n"
        "EQUITY: Share Capital | Retained Earnings | **Total Equity**\n"
        "✅CHECK: ≥20 rows. Do NOT collapse liabilities to single total.\n\n"
        "**CF items — output ALL:** "
        "OCF | ICF | FCF | **Net Change** | Opening Cash | FX Effect | **Closing Cash** "
        "✅CHECK: ≥7 rows.\n\n"

        "### C-2. Borrower Summary Statistics (MANDATORY)\n"
        "ALL categories required — do NOT omit any:\n"
        "**Profitability:** Gross Margin% | Op Margin% | NI Margin% | EBITDA Margin% | "
        "ROA% [annual] | ROE% [annual]\n"
        "**Leverage:** Total Debt (amt) | Net Debt (amt) | Debt/Equity(x) | "
        "Net Debt/Equity (or 'Net Cash') | Debt/EBITDA(x)\n"
        "**Coverage:** EBITDA/Interest(x) | OCF/Total Debt(x) | OCF/Interest(x)\n"
        "**Efficiency:** AR Days | AP Days | Inventory Days (if appl.)\n"
        "✅CHECK: ≥18 ratio rows.\n"
        "**CA Commentary:** 3-5 bullets — inflection points, benchmarks, "
        "forward credit view.\n\n"

        "### C-3. Guarantor Financials (CONDITIONAL)\n"
        "**Trigger:** guarantor_exists == true. "
        "**If false → SKIP entirely (no placeholder).**\n"
        "**Depth — MUST state in output:**\n"
        "- Critical guarantor (e.g. EMC for EMA) → 'Guarantor Depth: FULL' "
        "→ P&L+BS+CF+Stats same depth as Borrower.\n"
        "- Holding co. → 'Guarantor Depth: ABBREVIATED' → BS + Key Ratios only.\n\n"

        "### C-4. Guarantor Summary Statistics (CONDITIONAL)\n"
        "Trigger: guarantor_exists. Structure = C-2.\n\n"

        "### C-5. Base Case Projections (CONDITIONAL)\n"
        "**Trigger:** new_deal / asset_finance / project_finance.\n"
        "**a) Key Assumptions TABLE (not prose):** "
        "Revenue growth, COGS%, CAPEX, debt service, freight/lease rate, FX, "
        "interest rate.\n"
        "**b) Projected Financials TABLE:** "
        "P&L condensed (Rev→GP→OP→NI) + BS (Cash,Debt,Equity) + "
        "CF (OCF,CAPEX,Debt Svc,FCF). All years as columns.\n"
        "**c) DSCR TABLE:** | Period | OCF | Debt Service(P+I) | DSCR | "
        "— one row/year.\n"
        "**d) Conclusion (2-3 sentences):** serviceability, min DSCR, cash adequacy.\n"
        "✅CHECK: ≥3 tables in C-5.\n\n"

        "### C-6. Worse Case (CONDITIONAL)\n"
        "**Trigger: C-5 exists → C-6 is MANDATORY.**\n"
        "**a) Stress Assumptions TABLE:** "
        "| Assumption | Base | Worse | Stress Magnitude |\n"
        "**b) Stressed Summary TABLE:** "
        "Revenue, OP, NI, OCF, Cash, DSCR per year.\n"
        "**c) Conclusion:** DSCR>1.0x? Cash trough? Guarantor trigger? "
        "vs historical worst.\n"
        "✅CHECK: ≥2 tables in C-6.\n\n"

        "### C-7. Lessee Financials (CONDITIONAL)\n"
        "Trigger: aircraft_leasing + identifiable lessees. "
        "**If NOT triggered → SKIP entirely. No 'Not applicable'.**\n\n"

        "### C-8. Sensitivity Analysis (CONDITIONAL)\n"
        "Trigger: projections exist.\n"
        "**ALL 6 columns:** | Variable | Base Case | Stress | DSCR Min Impact | "
        "Cash Trough Impact | Conclusion |\n"
        "Variables: Freight -10/-20/-30% | Interest +100/+200bps | CAPEX +20% | "
        "FX ±10% | Delay +6/12M\n\n"

        "## D. Order\n"
        "7A → 7B → [7C → 7D] → [7E → 7F] → [7G] → [7H]\n\n"

        "## E. Formatting & Rules\n"
        "**Format:** English. Currency+Unit every table. Negatives: (1,234). "
        "Pct: 28.4%. Ratios: 0.64x. 'Net Cash' for negative net debt. "
        "Bold subtotals. Commas: 12,164,913.\n"
        "**N/M vs N/A:** Denominator ≤0 → N/M. "
        "Interim + annualization needed "
        "(ROA,ROE,Debt/EBITDA,EBITDA/Int,OCF/Debt,OCF/Int) → N/A. "
        "Interim + point-in-time (D/E, NetDebt/Eq) → calculate normally.\n"
        "**Commentary:** Every table 3-5 bullets. Cite numbers. YoY = absolute+%. "
        "Interim vs prior year. Flag one-offs. Forward-looking.\n"
        "**Projections:** Assumptions with source. DSCR every year. "
        "Worse Case=plausible. "
        "Conclusion=serviceability+minDSCR+cash. Compare to historical worst.\n\n"

        "## F. QA Gate — MANDATORY EXECUTION\n"
        "After drafting, EXECUTE all gates. If any fails → FIX before output.\n"
        "G1-Arithmetic: Rev-COGS=GP | P&L sums to NI | TA=TL+Eq | "
        "CA+NCA=TA, CL+NCL=TL | OCF+ICF+FCF+FX=ΔCash | Open+ΔCash=Close | "
        "CF Close=BS Cash | Ratios match data | DSCR=OCF/DS\n"
        "G2-Cross-Period: Close=next Open | RE movement≈NI-Div | "
        "Debt moves consistent\n"
        "G3-Cross-Entity: Borrower Rev<Guarantor Rev | "
        "Guarantor Eq>Borrower Eq (if parent)\n"
        "G4-Completeness: All ✅CHECK counts met | Commentary below every table | "
        "Full BS detail | Projections Base+Worse both present\n"
        "**Append to output:** `[QA] G1:✅/❌ G2:✅/❌ G3:✅/❌ G4:✅/❌`\n\n"

        "## G. Prohibitions\n"
        "1. No credit judgments (→§2) 2. No risk assessment language (→§2) "
        "3. No altering source data 4. No omitting commentary "
        "5. No mixing currencies in one table "
        "6. No ratios without underlying data shown "
        "7. No projections beyond 5-7yr(asset)/3-5yr(corporate) "
        "8. No omitting Worse Case if Base Case exists "
        "9. No inconsistent accounting bases without disclosure "
        "10. No completion markers ('✅Complete','Done') "
        "11. No source hyperlinks "
        "12. No conversational prompts ('If you want...') "
        "13. No placeholder sections ('Not applicable') for non-triggered conditionals "
        "14. Output = FINAL credit report. No meta-commentary.\n\n"

        "## H. Anti-Truncation Protocol\n"
        "**§7 expected: 5,000-10,000 tokens.**\n"
        "1. NEVER summarize tables — reproduce in FULL\n"
        "2. Commentary: min 2 bullets (never zero)\n"
        "3. If token limit reached → end with `[§7 CONTINUED — PART 2 FOLLOWS]`\n"
        "4. Split priority: 7A>7B>7E>7F>7C>7D>7H>7G\n"
        "5. NEVER replace tables with prose summaries"
    ),
    8: (
        "## A. Role\n"
        "Credit report engine for CUB SG Branch, producing **§8 Changes in Engaged Banks** — "
        "disclosing the Borrower's ACRA registered charges and banking relationships.\n"
        "**Scope:** §8 = ACRA Banking Charges ONLY. "
        "Other info (litigation, adverse news, sanctions, ESG) → §2/§4/§9. "
        "§8 is DATA-DRIVEN: Borrower SG-incorporated → ACRA available → produce full section. "
        "Borrower NOT SG-incorporated → 'Not Available' statement only.\n\n"

        "## B. Input\n"
        "`section_applicability`: Borrower jurisdiction + ACRA availability  "
        "`8A_acra_banking_charges`: ACRA search results + charges + commentary  "
        "`8B_other_information`: Reserved (currently not used)\n\n"

        "## C. Output Structure\n\n"

        "### C-0. Applicability Check (INTERNAL LOGIC — NOT output)\n"
        "Do NOT output an 'Applicability' heading or paragraph.\n"
        "If acra_data_available == false → Output ONLY:\n"
        "'8. Changes in Engaged Banks\\n[reason]' "
        "e.g., 'Not Available — Borrower is not incorporated in Singapore.' → STOP. "
        "No 8A or 8B.\n"
        "If acra_data_available == true → Output full 8A. "
        "Integrate jurisdiction into Search Metadata: "
        "'Based on ACRA search dated [date], [Entity] (UEN: [UEN]), a Singapore-incorporated "
        "company, has the following registered charges:' → 8B: SKIP entirely (see C-2).\n"
        "**Multiple borrowers (SPV):** Separate table per entity or combined with entity column.\n\n"

        "### C-1. ACRA Banking Charges\n"
        "**a) Search Metadata** (opening sentence, not separate section): "
        "'Based on ACRA search dated [date], [Entity] (UEN: [UEN]) has the following "
        "registered charges:'\n\n"
        "**b) Charges Table:**\n"
        "| # | Chargee | Date of Registration | Date of Charge | Amount (USD m) | "
        "Currency | Property Charged | Status |\n"
        "**Table Rules:**\n"
        "1. Chronological order — earliest first\n"
        "2. Status: 'Registered' or 'Satisfied ([DD MMM YYYY])'\n"
        "3. **CUB charges — annotate WITHIN the Property Charged cell:** "
        "e.g., 'Vessel — Hull No. 4508 — **CUB facility (Item 2, §1)**' "
        "Do NOT create separate 'Notes' section outside table.\n"
        "4. Amount: column header 'Amount (USD m)' with numeric values (e.g., 150.0)\n"
        "5. Property: brief + specific (Vessel — M/V [Name] | Hull No. [X] | "
        "Aircraft — [Type] MSN [X] | 'All present and future assets' for floating charge)\n"
        "6. No charges → 'No registered charges found for [Entity].'\n\n"
        "**c) Summary (below table — EXACT format):**\n"
        "Total charges: [X] ([Y] active, [Z] satisfied)\n"
        "Total active amount: USD [exact amount]m\n"
        "CUB charges: [N] totaling USD [exact amount]m\n"
        "Unique chargees: [ACRA names] ([M] distinct banking groups)\n"
        "**Precision:** Direct sum → exact number. No 'approximately' for calculated totals.\n"
        "**Same-bank:** If one bank has multiple branches, note: e.g., "
        "'7 chargees (6 groups — CUB SG + CUB HO = 1 group)'\n\n"
        "**d) CA Commentary (MANDATORY — 3-5 BULLET POINTS, NOT prose):**\n"
        "Each bullet = one theme, in order:\n"
        "1. **Volume & trend:** Charge count over time, pace, pattern "
        "(e.g., 'registered from Mar 2022 to Jan 2025, consistent with fleet expansion')\n"
        "2. **CUB position:** CUB charges with §1 Item refs + amounts. Confirm consistency.\n"
        "3. **Satisfied charges:** Context (vessel disposal / repayment / refinancing)\n"
        "4. **Charge type + banking quality:** All vessel mortgages vs floating charges. "
        "Bank profile (international/Japanese/local). Flag unknowns.\n"
        "5. **Red flags:** Explicitly 'No unusual patterns identified' if clean. "
        "OR flag: rapid increase, non-bank chargees, related-party, satisfy-re-register.\n"
        "6. **Forward-looking (MANDATORY if new_deal/renewal with new secured facility):** "
        "'Upon execution of proposed facility (Item [X], §1, USD [Y]m for [collateral]), "
        "an additional charge will be registered for CUB [Branch], "
        "bringing CUB total to [N+1] charges / USD [Z]m.'\n"
        "✅CHECK: ≥4 bullets. Bullet #6 MANDATORY for new_deal/renewal.\n\n"

        "### C-2. Other Information (RESERVED — NOT output)\n"
        "If 8B.applicable == false → **SKIP entirely. No text. No 'Not applicable'. "
        "No placeholder.**\n"
        "**PROHIBITION:** Never expose internal categories "
        "(litigation, sanctions, ESG list) in output.\n\n"

        "## D. Writing Rules\n"
        "**Tone:** English. Factual, neutral. Third person, past tense "
        "('ACRA search dated [date] returned...'). No credit judgment (→§2).\n"
        "**Conventions:** Chargee = ACRA registered name. Dates = DD MMM YYYY. "
        "Amounts = USD [X]m. UEN if available.\n"
        "**Commentary:** Bullet points only. Cite numbers. Cross-ref §1 for CUB. "
        "State 'no unusual patterns' explicitly if clean.\n\n"

        "## E. QA Gate — MANDATORY ACTIVE EXECUTION\n"
        "After drafting, EXECUTE all gates. If ANY fails → FIX before output.\n"
        "**G1 — Data Integrity:** All charges included, chronological, status accurate, "
        "amounts match input.\n"
        "**G2 — CUB Charges:** Annotated within table | Amounts match §1 | "
        "Collateral matches §1 | Count = §1 secured facilities | "
        "**New_deal → forward-looking bullet present**\n"
        "**G3 — Cross-Section:** §8 CUB ↔ §1 exact | §8 vessels ↔ §4/§5 | "
        "§8 chargees ↔ §1 banking relationships\n"
        "**G4 — Completeness:** Search date + UEN stated | 8 columns complete | "
        "Summary in exact format | ≥4 commentary bullets | Forward-looking if new_deal | "
        "'No unusual patterns' or flags stated\n"
        "**G5 — Red Flags:** Floating charges | Non-bank chargees | >2 new in 6 months | "
        "Related-party | Satisfy-re-register → all flagged if present\n"
        "**Append:** `[QA] G1:✅/❌ G2:✅/❌ G3:✅/❌ G4:✅/❌ G5:✅/❌`\n\n"

        "## F. Prohibitions\n"
        "1. No credit judgment (→§2) 2. No financial analysis (→§7) "
        "3. No fabricating ACRA data 4. No omitting any charge "
        "5. No duplicating §4/§2/§9 content 6. No 'Not Available' without reason "
        "7. No assuming ACRA = all banking (only registered charges) "
        "8. No confusing ACRA with JCIC/other bureaus 9. No source hyperlinks "
        "10. No conversational prompts ('If you want...') "
        "11. No sections not in output structure (no 'Applicability', no 'Notes') "
        "12. No exposing internal prompt categories 13. No completion markers "
        "14. Output = FINAL credit report. No meta-commentary."
    ),
    9: (
        "## A. Role\n"
        "Credit report engine for CUB SG Branch, producing **§9 Credit Analysis Checklist & Recommendation** — "
        "the definitive sign-off section of the credit memorandum.\n\n"
        "## B. Entity Validation Gate (C-0)\n"
        "Confirm the borrower entity from §4/§7 data before proceeding. "
        "If entity name or UEN is inconsistent across sections, flag [DATA CONFLICT] inline "
        "and use the §4 entity as the reference entity.\n\n"
        "## C. 23-Item Checklist Table (C-1)\n"
        "Produce a **23-item, 5-column** pipe table:\n"
        "| # | Category | Checklist Item | Response | Remarks |\n"
        "|---|---|---|---|---|\n\n"
        "**Response column MUST be one of:** **Yes** / **No\\*** / **N/A** (bold; "
        "use **No\\*** when qualified or subject to condition).\n"
        "Do NOT use ✓/✗ symbols.\n\n"
        "**Mandatory 23 items** (do NOT add, remove, or reorder):\n"
        "1. KYC & Compliance — CDD completed; state Tier classification\n"
        "2. Sanctions & AML — OFAC / MAS Sanctions List screening clear; state screening date\n"
        "3. PEP — No PEP identified; or state PEP name and mitigation if found\n"
        "4. Credit Risk — Internal MSR rating generated; state MSR level (e.g. MSR3)\n"
        "5. Credit Risk — Final MSR vs. external rating alignment; state both and divergence if any\n"
        "6. Credit Risk — Country risk rating acceptable; state CUB country risk rating\n"
        "7. Credit Risk — Industry risk acceptable; state CUB industry outlook\n"
        "8. Financial — Audited financials reviewed; state entity name and periods covered\n"
        "9. Financial — Base case minimum DSCR meets covenant; state exact figure and threshold\n"
        "10. Financial — Worse case minimum DSCR stated; state exact figure\n"
        "11. Collateral — Vessel valuation obtained; state valuer name and valuation date\n"
        "12. Collateral — ACR at delivery compliant; state ACR % vs. floor\n"
        "13. Collateral — VMC (Value Maintenance Clause) included; state cure period in Banking Days\n"
        "14. Collateral — Insurance requirements met (H&M, P&I, War Risk); CUB named loss payee confirmed\n"
        "15. Legal & Documentation — Banking Act s.33-3 compliance confirmed; "
        "state pre-delivery unsecured amount (USD m) and exemption basis\n"
        "16. Legal & Documentation — ACRA charges registered; state total charge count and CUB charge count\n"
        "17. Legal & Documentation — Legal opinions obtained; state jurisdictions and law firm names\n"
        "18. Legal & Documentation — Security documents executed or to be executed within stated timeframe\n"
        "19. ESG & Environmental — MSCI / Sustainalytics ESG risk rating reviewed; state rating and score\n"
        "20. ESG & Environmental — Poseidon Principles alignment confirmed; state CII rating\n"
        "21. ESG & Environmental — EU ETS applicability addressed; state scope and compliance route\n"
        "22. ESG & Environmental — IMO GHG / CII vessel rating at delivery; state rating letter\n"
        "23. Regulatory (MAS) — MAS 612 risk classification confirmed; state classification\n\n"
        "**Mandatory footnotes below the checklist table:**\n"
        "Item 15 footnote: '\\* Item 15: Pre-delivery unsecured drawdown of USD[X]m is within the "
        "Banking Act s.33-3 single-borrower unsecured limit. "
        "Exemption basis: [item (d) / other]. CUB internal approval reference: [ref].'\n"
        "Item 16 footnote: '\\* Item 16: ACRA charge search conducted on [date] for [entity name] "
        "(UEN: [UEN]). CUB charge(s): [Item #, §1 cross-reference].'\n\n"
        "## D. Conditions & Covenants Tables (C-2)\n"
        "Produce TWO flat pipe tables (no sub-numbering within items):\n\n"
        "**Table 1 — Conditions Precedent:**\n"
        "| No. | Description | Testing |\n"
        "|---|---|---|\n"
        "Testing column values: 'Before first drawdown' / 'Before vessel delivery' / 'Ongoing'\n\n"
        "**Table 2 — Ongoing Covenants:**\n"
        "| Description | Threshold/Requirement | Testing |\n"
        "|---|---|---|\n"
        "Include: ACR/VMC covenant, insurance, listing requirement, negative pledge, "
        "change of control, information undertakings.\n"
        "Below Table 2, state: '**Financial Covenants: NIL**' if none beyond ACR/DSCR.\n\n"
        "## E. Recommendation Block (C-3)\n"
        "Output using EXACT format (bold labels, one per line):\n\n"
        "**RECOMMENDATION:**\n\n"
        "**Decision:** APPROVE / APPROVE WITH CONDITIONS / DECLINE\n"
        "**Facility Amount:** USD [X]m\n"
        "**Tenor:** [X] years from first drawdown\n"
        "**Security Structure:** [1-2 sentence summary of collateral package]\n"
        "**Key Conditions:**\n"
        "1. [Condition]\n"
        "2. [Condition]\n"
        "**Balloon LTV:** [X]% (cap: [Y]%) — Compliant / Breach\n"
        "**Risk Level vs. Prior Review:** No change / Improved / Deteriorated — [reason]\n\n"
        "PROHIBITIONS in C-3:\n"
        "- Do NOT include 'Approval Authority' or any approving officer name\n"
        "- Do NOT write 'we recommend' or 'it is recommended'\n"
        "- Do NOT use 'satisfactory', 'low risk', 'manageable', 'well-mitigated', 'adequate'\n\n"
        "## F. Sign-Off Block (C-4)\n"
        "Output in plain text (NOT a table):\n\n"
        "Prepared by: [Name], [Title], Credit Management Department, CUB SG Branch\n"
        "Reviewed by: [Name], [Title], Credit Management Department, CUB SG Branch\n"
        "Date: [DD MMM YYYY]\n\n"
        "If names are not in input, use placeholders '[Prepared by]' and '[Reviewed by]'.\n\n"
        "## G. Quality Gate (QA)\n"
        "Run silent self-checks then append:\n"
        "G1 — All 23 checklist items present and in order\n"
        "G2 — Every Response is bold **Yes**/**No\\***/**N/A** (no ✓/✗ symbols)\n"
        "G3 — Item 15 footnote includes USD amount and §33-3 exemption basis\n"
        "G4 — Item 16 footnote includes search date, UEN, and CUB charge cross-reference\n"
        "G5 — Covenants table uses 'Testing' column header (NOT 'Frequency' or 'Status')\n"
        "G6 — RECOMMENDATION block has exact bold labels; no 'Approval Authority' line\n\n"
        "**Append to end of output:** `[QA] G1:✅/❌ G2:✅/❌ G3:✅/❌ G4:✅/❌ G5:✅/❌ G6:✅/❌`\n\n"
        "## H. Prohibitions\n"
        "1. Do NOT fabricate MSR ratings, DSCR figures, or ACR % — use only §7/§5 data\n"
        "2. Do NOT use 'satisfactory', 'low risk', 'manageable', 'well-mitigated', 'adequate'\n"
        "3. Do NOT write 'Approval Authority' or any approving officer name anywhere\n"
        "4. Do NOT use ✓/✗ symbols in Response column — bold **Yes**/**No\\***/**N/A** only\n"
        "5. Do NOT sub-number covenant items (e.g. 1.1, 1.2)\n"
        "6. Do NOT use 'banking days' — always 'Banking Days' (capital B, capital D)\n"
        "7. Do NOT omit either mandatory footnote (Items 15 and 16)\n"
        "8. Do NOT write a 'Financial Covenants' table unless covenants exist — state NIL\n"
        "9. Do NOT prefix recommendation with 'We recommend' or 'It is recommended'\n"
        "10. Do NOT include an 'approval authority' or 'credit committee' line\n"
        "11. Do NOT truncate — §9 must be 3,000–6,000 tokens\n"
        "12. Do NOT add or remove any of the 23 checklist items\n"
        "13. Do NOT use 'N/M' — use 'N/A' only\n"
    ),
    10: (
        "## A. Role\n"
        "Credit report engine for CUB SG Branch, producing **§10 Appendix** — "
        "supplementary data tables supporting §1–§9. "
        "**CRITICAL:** Appendix = FULL DETAIL. §7 may condense; §10 MUST expand. "
        "Every projection line item, every exposure row, every fleet data point must appear in full. "
        "NEVER compress or abbreviate Appendix tables.\n\n"
        "## B. Input\n"
        "- `10A_group_exposure`: CUB exposure by entity/branch\n"
        "- `10B_fleet_growth`: EMC capacity growth data\n"
        "- `10C_projections`: EMA detailed Base + Worse Case projections\n\n"
        "## C. Output Structure\n\n"
        "### C-0. Entity Validation (INTERNAL)\n"
        "Verify Borrower/Guarantor names match Input. If mismatch → STOP.\n\n"
        "### C-1. Section Title\n"
        '**"Appendix"** (no "10." prefix — Appendix is unnumbered per template)\n\n'
        "### C-2. Appendix I: CUB's Exposure to [Group Name]\n"
        "*Context line (italic, no 'Context' label):* "
        '"The following table supports Section 1: Credit Facility and Case Details (Group Limit)."\n'
        '"Unit: USD millions | As of: [Month Year]"\n\n'
        "**Single integrated Exposure Table with embedded subtotals — 10 columns:**\n"
        "| Entity | Branch | Facility Type | Current Approved | Proposed | Outstanding | "
        "Collateral | Guarantor | Maturity | MSR |\n\n"
        "**Table Rules:**\n"
        "1. New facilities marked: **[NEW]** bold in Facility Type cell 2\n"
        "2. Subtotal rows (**EMA Subtotal** / **EMC Subtotal** / **EVA Subtotal** / **Group Total**) "
        "embedded in same table, bold\n"
        "3. Blank separator rows between entity groups permitted\n"
        '4. Maturity: "Dec 2034E" format (not "Dec 2034 (est.)")\n'
        '5. Column header: "Current Approved" (not "Approved")\n'
        '6. MSR: "—" for entities not rated in this report\n\n'
        "**Group Limit sub-table** (below main table):\n"
        "| Item | Amount (USD m) |\n"
        "|---|---|\n"
        "Rows: Approved Group Limit | Proposed Total Exposure | **Utilization** (bold) | Headroom\n\n"
        "**EVA Note (MANDATORY if sister company included):**\n"
        '"_Note: [Sister Co.] is a sister company of [Guarantor] within [Group]. '
        "[Sister Co.] facilities are covered under a separate CA report and are included here "
        'for Group Limit purposes only._"\n\n'
        "### C-3. Appendix II: EMC Capacity Growth Targets ([Year Range])\n"
        "*Context line (italic):* "
        '"The following supports Section 4: Corporate History and Overview (Fleet Overview and Orderbook)."\n\n'
        "**Fleet Table — 5 columns (NOT 4):**\n"
        "| Year | Owned Fleet (TEU million) | Total Fleet (TEU million) | Total Vessels | **Owned %** |\n\n"
        "**Rules:**\n"
        '1. Years with estimates: suffix "E" (e.g., 2025E, 2026E)\n'
        "2. Owned % column MANDATORY (e.g., 63%, 67%...88%)\n"
        "3. CAGR line below table: bold figure\n"
        "**Chart Reference:** *[EMC Fleet Capacity Growth Chart — Source: [Source] [Date] / EMC Investor Presentation]*\n\n"
        "**Key Notes (MANDATORY — minimum 5 bullets):**\n"
        "1. Target capacity (end-year TEU)\n"
        "2. Owned fleet transition (from X% to Y%) — reduce charter reliance\n"
        "3. Newbuild delivery concentration + orderbook count + source\n"
        "4. CUB-financed vessel positioning (TEU, Hull No., delivery date)\n"
        "5. **EMC CAPEX plan (USD amount) + EMA capital commitment (USD amount + date)**\n"
        "✅CHECK: Note #5 (CAPEX) MUST be present. If missing → FIX.\n\n"
        "### C-4. Appendix III: EMA — Detailed Financial Projections\n"
        "*Context line (italic):* "
        '"The following supports Section 7: Financial Analysis (Base Case and Worse Case Projections)."\n\n'
        "*Entity: [Name] — Standalone | Currency: USD | Unit: USD'000*\n\n"
        "#### Key Assumptions Table\n"
        "| Assumption | FY[Y]E | FY[Y]E | ... |\n"
        "(1 row per assumption, all years listed individually — no 'Same')\n\n"
        "**Assumptions Narrative (MANDATORY — italic paragraph below table):**\n"
        '"_Revenue growth assumes [basis]. COGS reflects [basis]. CAPEX per [basis]._"\n\n'
        "#### Base Case — Projected P&L (MINIMUM 12 rows)\n"
        "MANDATORY line items: Revenue | Cost of Goods Sold | **Gross Profit** | "
        "Other Operating Income | Operating Expenses | **Operating Profit** | "
        "Finance Income | Finance Cost | Other Non-Operating | **Profit Before Tax** | "
        "Income Tax | **Net Income**\n"
        "- Subtotals (GP/OP/PBT/NI) in **bold**\n"
        "- Negative numbers in parentheses: (7,755,000)\n"
        "- ✅CHECK: P&L rows ≥ 12. If fewer → ADD missing rows.\n\n"
        "#### Base Case — Projected Balance Sheet (MINIMUM 16 rows)\n"
        "MANDATORY: Cash & Equivalents | Trade Receivables | Other Current Assets | "
        "**Total Current Assets** | Vessels & Equipment | Right-of-Use Assets | "
        "Other Non-Current Assets | **Total Non-Current Assets** | **Total Assets** | "
        "**Total Current Liabilities** | Long-term Borrowings | Non-Current Lease Liabilities | "
        "Other Non-Current Liabilities | **Total Non-Current Liabilities** | "
        "**Total Liabilities** | **Total Equity**\n"
        "- ✅CHECK: BS rows ≥ 16. If fewer → ADD.\n\n"
        "#### Base Case — Projected Cash Flow (MINIMUM 6 rows, SEPARATE table)\n"
        "MANDATORY: Operating Cash Flow | Investing Cash Flow | Financing Cash Flow | "
        "**Net Change in Cash** | Opening Cash | **Closing Cash**\n"
        "- ✅CHECK: CF rows ≥ 6. Closing Cash = Opening + Net Change.\n\n"
        "#### Base Case — DSCR Analysis (SEPARATE table from CF)\n"
        "| FY[Y]E | ... | OCF | Total Debt Service (P+I) | **DSCR** |\n"
        "(DSCR with 'x' suffix: e.g. 5.6x)\n\n"
        "**DSCR Commentary (MANDATORY — italic):**\n"
        '"_DSCR remains above [X]x throughout... Minimum DSCR of [X]x occurs in [years]._"\n\n'
        "#### Worse Case — Stress Assumptions (COMPARISON TABLE, not bullets)\n"
        "| Assumption | Base Case | Worse Case | Stress Magnitude |\n"
        "(Rows: Revenue, COGS%, SOFR, Dividend — minimum 4 rows)\n\n"
        "#### Worse Case — Stressed Summary Table\n"
        "Rows: Revenue | Operating Profit | Net Income | OCF | Cash Balance | **DSCR**\n\n"
        "**Worse Case Commentary (MANDATORY — italic):**\n"
        '"_Under Worse Case, DSCR declines to minimum [X]x in [year] but remains above 1.0x... '
        "Cash trough of USD[X] million in [year]. Net income remains positive in all years._\"\n\n"
        "## D. Writing Rules\n"
        "**Language:** English. "
        "**Numbers:** USD'000 with commas. Negatives in parentheses. "
        "**Bold:** Subtotal rows, DSCR, Group Total, [NEW], CAGR figure, Utilization. "
        "**Italic:** Context lines, narratives, commentaries. "
        'No "Context"/"System note" labels — use italic sentences directly. '
        '**Year suffix:** "E" for all estimated/projected years.\n\n'
        "## E. QA Gate — MANDATORY ACTIVE EXECUTION\n"
        "**G1 — Entity:** Borrower/Guarantor names correct throughout\n"
        "**G2 — Appendix I:** Subtotals embedded | EVA note present | Group Limit table present | "
        "Arithmetic: entity subtotals sum to Group Total\n"
        "**G3 — Appendix II:** 5 columns incl. Owned% | ≥5 Key Notes | CAPEX note present | Chart reference present\n"
        "**G4 — Appendix III line counts:** P&L ≥12 rows | BS ≥16 rows | CF ≥6 rows | "
        "DSCR separate table | Assumptions narrative present | DSCR commentary present | Worse Case commentary present\n"
        "**G5 — Arithmetic:** GP=Rev-COGS | TA=TCA+TNCA | TA=TL+TE | "
        "Closing Cash=Opening+Net Change | DSCR=OCF/Debt Service\n"
        "**G6 — Cross-section:** §10 DSCR=§7 DSCR | §10 Exposure=§1 facilities | §10 Fleet=§4 data\n\n"
        "**Append to end of output:** `[QA] G1-G6: ✅/❌`\n\n"
        "## F. Prohibitions\n"
        "1. No condensing Appendix III tables (this is the DETAIL version)\n"
        "2. No combining CF + DSCR into one table\n"
        "3. No 'Same' in assumption cells — list each year explicitly\n"
        "4. No source hyperlinks or file references\n"
        '5. No introductory meta-text ("Below is the complete...")\n'
        '6. No "✅ QA Status" blocks in output body\n'
        '7. No "Context" or "System note" labels\n'
        '8. No "10." prefix on section title\n'
        "9. No conversational prompts or completion markers\n"
        "10. Output = FINAL credit report appendix. No meta-commentary.\n\n"
        "## G. Anti-Truncation\n"
        "**§10 expected: 5,000–10,000 tokens.** This is the LONGEST section.\n"
        "1. NEVER truncate projection tables — all rows mandatory\n"
        "2. Mandatory minimums: P&L ≥12 | BS ≥16 | CF ≥6 | DSCR separate\n"
        "3. If token limit → split: `[§10 CONTINUED — PART 2]`\n"
        "4. Priority: Appendix III > Appendix I > Appendix II\n"
    ),
}

OUTPUT_INSTRUCTIONS = """\
## Output Instructions
- Write in clean Markdown with proper heading hierarchy
- Use ## for the section heading, ### for sub-sections
- Include tables where data permits (pipe-table syntax)
- All figures must come from the analyst input data or evidence excerpts above
- Do not fabricate or extrapolate numbers not present in the input
"""


def build_section_prompt(
    section_no: int,
    input_json: dict,
    evidence_chunks: list[str],
    preceding_outputs: Optional[dict[int, str]] = None,
    is_continuation: bool = False,
    continuation_resume_token: Optional[str] = None,
) -> tuple[str, str]:
    """
    Build (system_prompt, user_prompt) for a single section generation call.

    When is_continuation=True the user_prompt instructs the model to continue
    from where it left off, using the resume token as a prefix.
    """
    heading = SECTION_HEADINGS.get(section_no, f"Section {section_no}")
    instructions = SECTION_INSTRUCTIONS.get(section_no, f"Write {heading}.")

    evidence_block = ""
    if evidence_chunks:
        parts = ["\n\n## Evidence from Uploaded Documents\n"]
        for i, chunk in enumerate(evidence_chunks, 1):
            parts.append(f"--- Excerpt {i} ---\n{chunk}")
        evidence_block = "\n\n".join(parts)

    preceding_block = ""
    if preceding_outputs:
        parts = ["\n\n## Previously Generated Sections (for cross-reference)\n"]
        for sec_no, md in sorted(preceding_outputs.items()):
            preview = md[:600].rstrip()
            parts.append(f"### Section {sec_no} preview\n{preview}\n…")
        preceding_block = "\n\n".join(parts)

    if is_continuation and continuation_resume_token:
        user_prompt = (
            f"{continuation_resume_token}\n\n"
            f"Continue writing {heading} from where the previous output ended. "
            "Do not repeat content already written. Resume the Markdown output directly."
        )
    else:
        input_text = json.dumps(input_json, ensure_ascii=False, indent=2)
        user_prompt = (
            f"{instructions}\n\n"
            f"## Analyst Input Data\n\n```json\n{input_text}\n```"
            f"{evidence_block}"
            f"{preceding_block}\n\n"
            f"{OUTPUT_INSTRUCTIONS}"
        )

    return SYSTEM_PROMPT, user_prompt
